name: "S3 File Upload (BackBlaze)"
description: "Upload an object to an S3 bucket like backblaze."
author: "bm2ilabs"
runs:
  using: docker
  image: Dockerfile
branding:
  icon: arrow-up
  color: green
